wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
batch_size:
  desc: null
  value: 64
loss_fn:
  desc: null
  value: CE-Loss
lr:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: Adams
